
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oavljdrqfzliikfncrdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hdmxqZHJxZnpsaWlrZm5jcmRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NzY5MTMsImV4cCI6MjA2MjU1MjkxM30.zS09LYAVFaKjjn_LaPVGrZlEjNK8baN3q20hXuNBljs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce'
    },
    global: {
      headers: {
        'x-client-info': 'supabase-js-web/2.49.4'
      }
    }
  }
);
